jobs:
- name: testflight
  serial: true
  plan:
  - get: testflight
    trigger: true
  - task: render-secrets
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bodymindarts/cepler-templates
          tag: 0.1.0
      outputs:
      - name: secrets
      params:
        SECRETS:
          github_private_key: ((github.private_key))
      run:
        path: sh
        args:
        - -c
        - |
          cat <<EOF > secrets/values.yml
          #@data/values
          ---
          ${SECRETS}
  - do:
    - task: execute
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: bodymindarts/cepler-templates
            tag: latest
        inputs:
        - name: testflight
          path: repo
        - name: secrets
        outputs:
        - name: repo
        params:
          KAPP_KUBECONFIG_YAML:
            apiVersion: v1
            kind: Config
            preferences: {}
            clusters:
            - name: testflight
              cluster:
                certificate-authority-data: testflight.ca
                server: testflight.server
            users:
            - name: testflight-user
              user:
                token: token
            contexts:
            - name: testflight
              context:
                cluster: testflight
                user: testflight-user
            current-context: testflight
        run:
          dir: repo
          path: sh
          args:
          - -c
          - ytt -f examples/kapp/k8s -f ../secrets/values.yml | kapp -y deploy -f - -a testflight
  - put: testflight-out
    params:
      repository: repo
- name: staging
  serial: true
  plan:
  - get: staging
    trigger: true
  - task: render-secrets
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bodymindarts/cepler-templates
          tag: 0.1.0
      outputs:
      - name: secrets
      params:
        SECRETS:
          github_private_key: ((github.private_key))
      run:
        path: sh
        args:
        - -c
        - |
          cat <<EOF > secrets/values.yml
          #@data/values
          ---
          ${SECRETS}
  - do:
    - task: execute
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: bodymindarts/cepler-templates
            tag: latest
        inputs:
        - name: staging
          path: repo
        - name: secrets
        outputs:
        - name: repo
        params:
          KAPP_KUBECONFIG_YAML:
            apiVersion: v1
            kind: Config
            preferences: {}
            clusters:
            - name: staging
              cluster:
                certificate-authority-data: staging.ca
                server: staging.server
            users:
            - name: staging-user
              user:
                token: token
            contexts:
            - name: staging
              context:
                cluster: staging
                user: staging-user
            current-context: staging
        run:
          dir: repo
          path: sh
          args:
          - -c
          - ytt -f examples/kapp/k8s -f ../secrets/values.yml | kapp -y deploy -f - -a staging
  - put: staging-out
    params:
      repository: repo
resources:
- name: testflight
  type: cepler-in
  source:
    uri: git@github.com:bodymindarts/cepler-templates
    branch: main
    private_key: ((github.private_key))
    environment: testflight
    config: examples/kapp/cepler.yml
- name: testflight-out
  type: cepler-in
  source:
    uri: git@github.com:bodymindarts/cepler-templates
    branch: main
    private_key: ((github.private_key))
    environment: testflight
    config: examples/kapp/cepler.yml
- name: staging
  type: cepler-in
  source:
    uri: git@github.com:bodymindarts/cepler-templates
    branch: main
    private_key: ((github.private_key))
    environment: staging
    config: examples/kapp/cepler.yml
- name: staging-out
  type: cepler-in
  source:
    uri: git@github.com:bodymindarts/cepler-templates
    branch: main
    private_key: ((github.private_key))
    environment: staging
    config: examples/kapp/cepler.yml
resource_types:
- name: cepler-in
  type: registry-image
  source:
    repository: cepler/cepler-concourse-resource
    tag: 0.4.0
- name: cepler-out
  type: registry-image
  source:
    repository: cepler/cepler-concourse-resource
    tag: 0.4.0
