#@ load("values.star","values")
#@ load("github/base.lib.yml", "github")
#@ load("concourse/base.lib.yml", "concourse")

#@ if values["ci"]["driver"]["type"] == "github":
--- #@ github(values["ci"], values["cepler"])
#@ end
#@ if values["ci"]["driver"]["type"] == "concourse":
--- #@ concourse(values["ci"], values["cepler"])
#@ end
