name: cepler-deploy
"on":
- push
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        config_path: examples/github-ytt-kapp/cepler.yml
        environment: staging
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: k14s/setup-k14s-action@v1
      with:
        only: ytt, kapp
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: ytt -f examples/ytt-k8s > rendered.yml
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: cat rendered.yml
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        config_path: examples/github-ytt-kapp/cepler.yml
        environment: production
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: k14s/setup-k14s-action@v1
      with:
        only: ytt, kapp
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: ytt -f examples/ytt-k8s > rendered.yml
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      run: cat rendered.yml
