name: cepler-deploy
"on":
- push
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        environment: staging
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: Deploy
      run: echo "The time was ${{ steps.prepare-cepler.outputs.needs_deploying }}"
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: bodymindarts/cepler-action@main
      with:
        environment: testflight
        record: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - id: prepare-cepler
      uses: bodymindarts/cepler-action@main
      with:
        environment: production
        prepare: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: Deploy
      run: echo "The time was ${{ steps.prepare-cepler.outputs.needs_deploying }}"
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      uses: bodymindarts/cepler-action@main
      with:
        environment: testflight
        record: true
    - if: ${{ steps.prepare-cepler.outputs.needs_deploying == 'true' }}
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
